# Generated by Django 4.2.1 on 2023-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unidad_empaque', models.DecimalField(decimal_places=4, max_digits=16)),
                ('proveedor', models.CharField(max_length=300)),
                ('estado', models.BinaryField(default=1)),
            ],
        ),
    ]
