# Generated by Django 3.2.5 on 2023-05-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('nivel_inventario', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('almacen', models.CharField(max_length=300)),
                ('proveedor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('peso', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unidad_empaque', models.DecimalField(decimal_places=4, max_digits=16)),
                ('proveedor', models.CharField(max_length=300)),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reposicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('nivel_inventario_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('nivel_inventario_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('almacen', models.CharField(max_length=300)),
                ('nivel_inventario_actual', models.ForeignKey(db_column='nivel_inventario', on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_movimiento', models.CharField(max_length=300)),
                ('salidas', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('entradas', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('nivel_inventario_final', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('almacen', models.CharField(max_length=300)),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='sku',
            field=models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos'),
        ),
    ]
