# Generated by Django 4.2.1 on 2023-05-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('nivel_inventario', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('almacen', models.CharField(max_length=300)),
                ('proveedor', models.CharField(max_length=300)),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='reposicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('nivel_inventario_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('nivel_inventario_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('almacen', models.CharField(max_length=300)),
                ('nivel_inventario_actual', models.ForeignKey(db_column='nivel_inventario', on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_movimiento', models.CharField(max_length=300)),
                ('salidas', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('entradas', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('nivel_inventario_final', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('almacen', models.CharField(max_length=300)),
                ('sku', models.ForeignKey(db_column='sku', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
    ]
